Spendy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('transactions/', include('transactions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from . import views

app_name = 'transactions'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search_transactions, name='search_transactions'),
    path('add-income/', views.add_income, name='add_income'),
    path('add-expense/', views.add_expense, name='add_expense'),
    path('delete/<str:transaction_id>/', views.delete_transaction, name='delete_transaction'),
    path('edit-income/edit/<uuid:transaction_id>/', views.edit_income, name='edit_income'),
    path('edit-expense/edit/<uuid:transaction_id>/', views.edit_expense, name='edit_expense'),
    path('credit/', views.credit, name='credit'),
    path('credit/edit/<uuid:credit_id>/', views.edit_credit, name='edit_credit'),
    path('credit/delete/<uuid:credit_id>/', views.delete_credit, name='delete_credit'),
    path('deposit/', views.deposit, name='deposit'),
    path('deposit/edit/<uuid:deposit_id>/', views.edit_deposit, name='edit_deposit'),
    path('deposit/delete/<uuid:delete_id>/', views.delete_deposit, name='delete_deposit'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("login/", views.sing_in, name="login"),
    path("register/", views.sing_up, name="register"),
    path("logout/", views.sign_out, name="logout"),
]

essentials/templates/elements/navigation.html
{% load static %}
<div class="navbar-bg">
  <div class="" >
    <nav class="navbar navbar-expand-lg navbar-custom">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'transactions:home' %}">
          <img
            src="{% static 'imgs/spendy.png' %}"
            alt="logo"
            class="sidebar-logo"
          />
        </a>

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse m-auto" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex justify-content-between">
            <div class="d-flex flex-column flex-lg-row gap-lg-4">
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}" target="_blank">
                Admin
              </a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item ">
                <p class="nav-link fw-bolder" id="rate">
                    Balance: {{ user_balance.amount }}$
                </p>
            </li>
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'transactions:credit' %}">
                    Credit
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'transactions:deposit' %}">
                    Deposit
                </a>
            </li>
            <li class="nav-item ">

                <select class="form-select" aria-label="Default select example">
                  <option selected disabled>Privat24 API</option>
                  <option value="1 " disabled>Exchange Rate Buy/Sell</option>
                  <option value="2">USD {{ usd_buy }} / {{ usd_sell }}</option>
                  <option value="3">EUR {{ eur_buy }} / {{ eur_sell }}</option>
                </select>
            </li>


            </div>
            <div class="d-flex gap-2">
              <li class="nav-item">
                <a class="nav-link " type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" ><img class="navbar-icon mi-custom3" src="{% static 'imgs/profile.svg' %}" alt="profile"></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}"><img class="navbar-icon" src="{% static 'imgs/logout.svg' %}" alt="logout"></a>
              </li>
            </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Coming Soon! 🥳</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        This feature is coming soon! Be the first one to test it out 😎
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}"> Sign In </a>
            </li>
        {% endif %}

      </ul>
    </div>
  </div>
  <script src="../../static/navigation.js"></script>
</nav>
  </div>
</div>