Spendy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('transactions/', include('transactions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from . import views

app_name = 'transactions'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search_transactions, name='search_transactions'),
    path('add-income/', views.add_income, name='add_income'),
    path('add-expense/', views.add_expense, name='add_expense'),
    path('delete/<str:transaction_id>/', views.delete_transaction, name='delete_transaction'),
    path('edit-income/edit/<uuid:transaction_id>/', views.edit_income, name='edit_income'),
    path('edit-expense/edit/<uuid:transaction_id>/', views.edit_expense, name='edit_expense'),
    path('credit/', views.credit, name='credit'),
    path('credit/edit/<uuid:credit_id>/', views.edit_credit, name='edit_credit'),
    path('credit/delete/<uuid:credit_id>/', views.delete_credit, name='delete_credit'),
    path('deposit/', views.deposit, name='deposit'),
    path('deposit/edit/<uuid:deposit_id>/', views.edit_deposit, name='edit_deposit'),
    path('deposit/delete/<uuid:delete_id>/', views.delete_deposit, name='delete_deposit'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("login/", views.sing_in, name="login"),
    path("register/", views.sing_up, name="register"),
    path("logout/", views.sign_out, name="logout"),
]

essentials/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Spendy{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
    {% include 'elements/navigation.html' %}
    <div class="mt-4 container">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags ==  'success' %}
                <div class="row">
                    <div class="alert alert-success alert-dismissible fade show col-10 offset-1" role="alert">
                        <strong>Hooray! </strong> {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>
                {% else %}
                <div class="row">
                    <div class="alert alert-danger alert-dismissible fade show col-10 offset-1" role="alert">
                        <strong>Oops! </strong> {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>
                {% endif %}

            {% endfor %}
        {% endif %}
        {% block body %}{% endblock %}
    </div>



    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
</body>
</html>

essentials/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
{% if user.is_authenticated %}
<div class="row">
  <div class="col-lg-6 col-md-6 col-sm-12 offset-lg-1 home_responsivnes" style=";">
    <div class="mb-4 section-title text-center fs-1">General</div>
    <form action="{% url 'transactions:search_transactions' %}" method="GET">
    <div class="d-flex flex-row justify-content-between">
      <p>From</p>
      <p style="margin-right: 8.5rem">To</p>
    </div>
    <div class="d-flex flex-row justify-content-center mb-4 h5">
      <input type="date" id="date-start" name="from_date" />
      <strong>/</strong>
      <input type="date" id="date-end" name="to_date" />
    </div>
    <button type="submit" class="btn btn-outline-primary mb-5" style="width: 100%">Search ✔️</button>
    </form>
    <div class="diagram"></div>
    <div class="section-title">Total:</div>
    <div class="custom-list">
      <div class="mb-4 d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center">
          <div class="list-bullet" id="dark-green"></div>
          <div class="section-title">Income</div>
        </div>
        <div class="income-info btn btn-outline-warning"><a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">+$$$$$$</a></div>
      </div>
      <div class="d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center">
          <div class="list-bullet" id="light-green"></div>
          <div class="section-title">Expenses</div>
        </div>
        <div class="expenses-info btn btn-outline-warning"><a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">-$$$$$$</a></div>
      </div>
    </div>
    <div class="d-flex flex-column gap-4 btns-wrapper">
        <a href="{% url 'transactions:add_income'  %}" class="btn home-button mx-auto" style="width: 100%">Add Income</a>
        <a href="{% url 'transactions:add_expense' %} " class="btn  home-button mx-auto" style="width: 100%">Add Expense</a>
    </div>
  </div>
  <div class="col-lg-6 col-md-6 col-sm-12 offset-lg-1 mt-4 mt-md-0 shadow p-3 rounded home_responsivnes second_div">
    <div class="d-flex flex-row justify-content-between">
      <div class="mb-3 section-title">Transaction history:</div>
    </div>
    {% if transactions %}
        <div class="table">
            {% for transaction in transactions reversed %}
            <div class="table-row d-flex flex-row justify-content-between align-items-center border-bottom">
              <div class="transaction-price">{{ transaction.amount }}$</div>
              <div class="transaction-date">{{ transaction.created_at }}</div>
              <div class="transaction-category">{{ transaction.category }}</div>
              <div class="d-flex">
{#                  <p style="font-size: 10px" class="text-success">I</p>#}
                <a href="{% url 'transactions:edit_income' transaction.id %}" class="icon-edit mi-custom">
                  <img src="{% static 'imgs/Edit.svg' %}" alt="edit-icon" >
                </a>
{#                  <p style="font-size: 10px" class="text-danger">E</p>#}
                <form class="mi-custom2" action="{% url 'transactions:delete_transaction' transaction.id %}" method="POST">
                  {% csrf_token %}
                    <a type="submit" href="{% url 'transactions:edit_expense' transaction.id %}" class="icon-edit">
                      <img src="{% static 'imgs/Edit.svg' %}" alt="edit-icon">
                    </a>
                </form>

                <a href="{% url 'transactions:delete_transaction' transaction.id %}" class="icon-bin mi-custom2">
                  <img src="{% static 'imgs/Bin.svg' %}" alt="bin-icon">
                </a>
              </div>
            </div>
            {% endfor %}
        </div>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Coming Soon! 🥳</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                This feature is coming soon! Be the first one to test it out 😎
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
    {% endif %}
  </div>
</div>
{% else %}
<h1>Welcome! ⭐️</h1>
<h2>To gain full access, please login <a href="{% url 'users:login' %}">here</a></h2>
{% endif %}
{% endblock %}