Spendy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('transactions/', include('transactions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from . import views

app_name = 'transactions'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search_transactions, name='search_transactions'),
    path('add-income/', views.add_income, name='add_income'),
    path('add-expense/', views.add_expense, name='add_expense'),
    path('delete/<str:transaction_id>/', views.delete_transaction, name='delete_transaction'),
    path('edit-income/edit/<uuid:transaction_id>/', views.edit_income, name='edit_income'),
    path('edit-expense/edit/<uuid:transaction_id>/', views.edit_expense, name='edit_expense'),
    path('credit/', views.credit, name='credit'),
    path('credit/edit/<uuid:credit_id>/', views.edit_credit, name='edit_credit'),
    path('credit/delete/<uuid:credit_id>/', views.delete_credit, name='delete_credit'),
    path('deposit/', views.deposit, name='deposit'),
    path('deposit/edit/<uuid:deposit_id>/', views.edit_deposit, name='edit_deposit'),
    path('deposit/delete/<uuid:delete_id>/', views.delete_deposit, name='delete_deposit'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("login/", views.sing_in, name="login"),
    path("register/", views.sing_up, name="register"),
    path("logout/", views.sign_out, name="logout"),
]

transactions/models.py
import uuid

from django.db import models
from users.models import User


# Create your models here.


class Balance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=15, default=0, decimal_places=3)
    updated_at = models.DateTimeField(auto_now=True)


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Transaction(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    balance = models.ForeignKey(Balance, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=15, default=0, decimal_places=3)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # type = models.BooleanField


class CreditDeposit(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    balance = models.ForeignKey(Balance, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=15, default=0, decimal_places=3)
    years = models.IntegerField(default=1)
    income = models.DecimalField(max_digits=15, default=0, decimal_places=3)
    profit = models.DecimalField(max_digits=15, default=0, decimal_places=3)
    percentage = models.DecimalField(max_digits=5, default=0, decimal_places=1)

transactions/views.py
import requests
from decimal import Decimal

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import datetime, date

from .models import Balance, Transaction, Category, CreditDeposit


def home(request):
    context = {}
    if request.user.is_authenticated:

        user_balance = Balance.objects.get(user=request.user)
        transactions = Transaction.objects.filter(balance=user_balance)
        context = {
            'home_page': True,
            'transactions': transactions,
        }

    return render(request, 'home.html', context=context)


@login_required
def search_transactions(request):
    from_date_str = request.GET.get('from_date')
    to_date_str = request.GET.get('to_date')

    if from_date_str or to_date_str:
        transactions = Transaction.objects.all()

        if from_date_str:
            from_date = datetime.strptime(from_date_str, '%Y-%m-%d').date()
            transactions = transactions.filter(created_at__date__gte=from_date)

        if to_date_str:
            to_date = datetime.strptime(to_date_str, '%Y-%m-%d').date()
            transactions = transactions.filter(created_at__date__lte=to_date)

        transactions = transactions.order_by('created_at')

        context = {
            'transactions': transactions,
        }
        messages.success(request, "Search went successfully! 🥳")
        return render(request, 'home.html', context)

    messages.error(request, "Sorry, from_date or to_date is not provided >_<")
    return redirect('transactions:home')


@login_required
def add_income(request):

    if request.method == 'POST':
        category_id = request.POST['income_category']
        amount = Decimal(request.POST['income_amount'])
        user_balance = Balance.objects.get(user=request.user)

        transaction = Transaction(
            balance=user_balance,
            category=Category.objects.get(id=category_id),
            amount=amount,
        )
        transaction.save()

        user_balance.amount += transaction.amount
        user_balance.save()

        messages.success(request, "Transaction Added Successfully ⭐️")
        return redirect('transactions:home')

    categories = Category.objects.order_by('name')
    context = {
        'categories': categories,
    }

    return render(request, 'transactions/add_income.html', context=context)


@login_required
def edit_income(request, transaction_id):
    transaction = Transaction.objects.get(id=transaction_id)
    categories = Category.objects.order_by('name')

    if request.method == 'POST':
        category_id = request.POST['income_category']
        amount = Decimal(request.POST['income_amount'])

        user_balance = transaction.balance
        user_balance.amount -= transaction.amount  # Deduct the previous income amount

        transaction.category = Category.objects.get(id=category_id)
        transaction.amount = amount

        user_balance.amount += amount  # Add the updated income amount
        user_balance.save()
        transaction.save()

        messages.success(request, "Transaction Edited Successfully ⭐️")

        return redirect('transactions:home')

    context = {
        'transaction': transaction,
        'categories': categories,
    }

    return render(request, 'transactions/edit_income.html', context=context)


@login_required
def edit_expense(request, transaction_id):
    transaction = Transaction.objects.get(id=transaction_id)
    categories = Category.objects.order_by('name')

    if request.method == 'POST':
        category_id = request.POST['expense_category']
        amount = Decimal(request.POST['expense_amount'])

        user_balance = transaction.balance
        user_balance.amount += transaction.amount  # Add back the previous expense amount

        transaction.category = Category.objects.get(id=category_id)
        transaction.amount = amount

        user_balance.amount -= amount  # Deduct the updated expense amount
        user_balance.save()
        transaction.save()

        messages.success(request, "Transaction Edited Successfully ⭐️")
        return redirect('transactions:home')

    context = {
        'transaction': transaction,
        'categories': categories,
    }

    return render(request, 'transactions/edit_expense.html', context=context)


@login_required
def add_expense(request):

    if request.method == 'POST':
        category_id = request.POST['expense_category']
        amount = Decimal(request.POST['expense_amount'])
        user_balance = Balance.objects.get(user=request.user)

        transaction = Transaction(
            balance=user_balance,
            category=Category.objects.get(id=category_id),
            amount=amount,
        )
        transaction.save()

        user_balance.amount -= transaction.amount
        user_balance.save()

        messages.success(request, "Transaction Added Successfully ⭐️")
        return redirect('transactions:home')

    categories = Category.objects.order_by('name')
    context = {
        'categories': categories,
    }

    return render(request, 'transactions/add_expense.html', context=context)


@login_required
def delete_transaction(request, transaction_id):
    transaction = get_object_or_404(Transaction, id=transaction_id)
    transaction.delete()

    messages.success(request, "Transaction Deleted Successfully 😎")
    return redirect('transactions:home')


@login_required
def credit(request):
    if request.method == 'POST':
        amount = request.POST['credit_amount']
        income = request.POST['credit_income']
        loss = request.POST['credit_loss']

        credit = CreditDeposit(
            balance=Balance.objects.get(user=request.user),
            amount=amount,
            income=income,
            profit=loss,
            percentage=13.9,
        )
        credit.save()

        messages.success(request, "Credit Added Successfully 👾!")
        return redirect('transactions:credit')

    credits = CreditDeposit.objects.filter(balance__user=request.user)

    context = {
        'credits': credits
    }

    return render(request, 'transactions/credit_deposit/credit.html', context=context)


@login_required
def edit_credit(request, credit_id):
    credit = get_object_or_404(CreditDeposit, id=credit_id)

    if request.method == 'POST':
        amount = request.POST['credit_amount']
        income = request.POST['credit_income']
        loss = request.POST['credit_loss']

        credit.amount = amount
        credit.income = income
        credit.profit = loss
        credit.save()

        messages.success(request, "Credit Updated Successfully 👾!")
        return redirect('transactions:credit')

    context = {
        'credit': credit
    }

    return render(request, 'transactions/credit_deposit/edit_credit.html', context=context)


@login_required
def delete_credit(request, credit_id):
    if request.method == 'GET':
        credit = get_object_or_404(CreditDeposit, id=credit_id)
        credit.delete()
        messages.success(request, "Transaction Deleted Successfully 👾!")
    return redirect('transactions:credit')


@login_required
def deposit(request):
    if request.method == 'POST':
        amount = request.POST['deposit_amount']
        income = request.POST['deposit_income']
        profit = request.POST['deposit_profit']

        deposit = CreditDeposit(
            balance=Balance.objects.get(user=request.user),
            amount=amount,
            income=income,
            profit=profit,
            percentage=11.5,
        )
        deposit.save()

        messages.success(request, "Deposit Added Successfully 👾!")

    deposits = CreditDeposit.objects.filter(balance__user=request.user)

    context = {
        'deposits': deposits
    }

    return render(request, 'transactions/credit_deposit/deposit.html', context=context)


@login_required
def edit_deposit(request, deposit_id):
    deposit = get_object_or_404(CreditDeposit, id=deposit_id)

    if request.method == 'POST':
        amount = request.POST['deposit_amount']
        income = request.POST['deposit_income']
        profit = request.POST['deposit_profit']

        deposit.amount = amount
        deposit.income = income
        deposit.profit = profit
        deposit.save()

        messages.success(request, "Deposit Updated Successfully 👾!")
        return redirect('transactions:deposit')

    context = {
        'deposit': deposit
    }

    return render(request, 'transactions/credit_deposit/edit_deposit.html', context=context)


@login_required
def delete_deposit(request, delete_id):
    if request.method == 'GET':
        deposit = CreditDeposit.objects.get(id=delete_id)
        deposit.delete()
        messages.success(request, "Transaction Deleted Successfully 👾!")
    return redirect('transactions:deposit')

essentials/templates/transactions/credit_deposit/credit.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="row">
    <div class="col-lg-10 col-md-10 col-sm-10 mx-auto">
        <div class="income-form shadow border-top rounded mb-5">
            <h1 class="page-name text-center">Credit</h1>
            <form method="POST">
              {% csrf_token %}
              <div class="mb-3">
                <div class="upperText">
                  <label for="inputNumber" class="form-label">Amount</label>
                  <input type="number" class="rangeNum" name="credit_amount" id="inputNumber" value="0" min="0" max="100000" oninput="cloneValue(this.value)">
                </div>
                <input type="range" class="range" id="range" min="0" max="100000" step="1" value="0" oninput="getRange(this.value)" />
                <div class="lowerText1">
                  <label class="form-label text-center">0</label>
                  <label class="form-label text-center">100 000</label>
                </div>
                <div class="lowerText2">
                  <label class="form-label text-center">
                    Yearly Amount<br>
                    <p id="potentialIncome">0</p>
                    <input type="hidden" name="credit_income" value="0" id="depositIncomeField">
                  </label>
                  <label class="form-label text-center">
                    Loss<br>
                    <p id="profitValue">0</p>
                    <input type="hidden" name="credit_loss" value="0" id="depositProfitField">
                  </label>
                  <label class="form-label text-center">
                    Annual percentage<br>
                    13.9 %
                  </label>
                </div>
              </div>

              <div class="d-flex justify-content-center gap-3">
                <button type="submit" class="btn home-button" style="width: 100%;">Add</button>
                <a type="button" href="{% url 'transactions:home' %}" class="btn btn-cancel" style="width: 100%;">Cancel</a>
              </div>
            </form>
        </div>
    </div>
</div>
{% if credits %}
    <div class="row">
        <h2>Transactions:</h2>
        <div class="col-lg-12 col-md-12 col-sm-12 mt-5 d-flex justify-content-center">
            <div class="table-responsive" style="width: 100%">
                <table class="table text-center">
                    <tbody class="justify-content-between " >
                        <tr>
                            <th class="col">Investment $</th>
                            <th class="col">Percentage</th>
                            <th class="col">Loss per year</th>
                            <th class="col">Edit</th>
                            <th class="col">Delete</th>
                        </tr>
                        {% for credit in credits reversed %}
                            <tr>
                                <th class="">{{ credit.amount }}$</th>
                                <td>{{ credit.percentage }}%</td>

                                    {% if credit.percentage == 11.5 %}
                                        <td class="text-success">+{{ credit.profit }}$</td>
                                    {% else %}
                                        <td class="text-danger">-{{ credit.profit }}$</td>
                                    {% endif %}

                                <td><a href="{% url 'transactions:edit_credit' credit.id %}" type="submit" class="btn ">
                                    <img src="{% static 'imgs/Edit.svg' %}" alt="edit">
                                </a></td>
                                <td><a href="{% url 'transactions:delete_credit' credit_id=credit.id %}" type="submit" class="btn">
                                    <img src="{% static 'imgs/Bin.svg' %}" alt="delete">
                                </a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endif %}

<script>
function percentage(percent, total) {
  return ((parseFloat(total) / 100) * percent).toFixed(2);
}

function getRange(val) {
  const result = parseFloat(val) + parseFloat(percentage(13.9, val));
  document.getElementById("potentialIncome").innerHTML = result;
  document.getElementById("inputNumber").value = val;
  document.getElementById("profitValue").innerText = parseFloat(percentage(13.9, val));

  // Update hidden input field values
  document.getElementById("depositIncomeField").value = result;
  document.getElementById("depositProfitField").value = parseFloat(percentage(13.9, val));
}

function cloneValue(val) {
  if (val > 100000) {
    val = 100000;
    inputNumber.value = val;
  } else if (val <= 0) {
    val = 0;
    inputNumber.value = val;
  }
  document.getElementById("range").value = val;
  const result = parseFloat(val) + parseFloat(percentage(13.9, val));
  document.getElementById("potentialIncome").innerHTML = result.toFixed(2);
  document.getElementById("profitValue").innerText = parseFloat(percentage(13.9, val));

  // Update hidden input field values
  document.getElementById("depositIncomeField").value = result.toFixed(2);
  document.getElementById("depositProfitField").value = parseFloat(percentage(13.9, val));
}

</script>

{% endblock %}

essentials/templates/transactions/credit_deposit/deposit.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="row">
    <div class="col-lg-10 col-md-10 col-sm-10 mx-auto">
        <div class="income-form shadow border-top rounded mb-5">
            <h1 class="page-name text-center">Deposit</h1>
            <form method="POST">
                  {% csrf_token %}
                  <div class="mb-3">
                    <div class="upperText">
                      <label for="inputNumber" class="form-label">Amount</label>
                      <input type="number" class="rangeNum" name="deposit_amount" id="inputNumber" value="0" min="0" max="100000" oninput="cloneValue(this.value)">
                    </div>
                    <input type="range" class="range" id="range" min="0" max="100000" step="1" value="0" oninput="getRange(this.value)" />
                    <div class="lowerText1">
                      <label class="form-label text-center">0</label>
                      <label class="form-label text-center">100 000</label>
                    </div>
                    <div class="lowerText2">
                      <label class="form-label text-center">
                        Yearly Income<br>
                        <p id="potentialIncome">0</p>
                        <input type="hidden" name="deposit_income" value="0" id="depositIncomeField">
                      </label>
                      <label class="form-label text-center">
                        Profit<br>
                        <p id="profitValue">0</p>
                        <input type="hidden" name="deposit_profit" value="0" id="depositProfitField">
                      </label>
                      <label class="form-label text-center">
                        Annual percentage<br>
                        11.5 %
                      </label>
                    </div>
                  </div>

                  <div class="d-flex justify-content-center gap-3">
                    <button type="submit" class="btn home-button" style="width: 100%;">Add</button>
                    <a type="button" href="{% url 'transactions:home' %}" class="btn btn-cancel" style="width: 100%;">Cancel</a>
                  </div>
                </form>
        </div>
    </div>
</div>
{% if deposits %}
    <div class="row">
        <h2>Transactions:</h2>
        <div class="col-lg-12 col-md-12 col-sm-12 mt-5 d-flex justify-content-center">
            <div class="table-responsive" style="width: 100%">
                <table class="table text-center">
                    <tbody class="justify-content-between " >
                    <tr>
                        <th class="col">Investment $</th>
                        <th class="col">Percentage</th>
                        <th class="col">Profit a year</th>
                        <th class="col">Edit</th>
                        <th class="col">Delete</th>
                    </tr>
                    {% for deposit in deposits reversed %}
                        <tr>
                            <th class="">{{ deposit.amount }}$</th>
                            <td>{{ deposit.percentage }}%</td>
                            {% if deposit.percentage == 11.5 %}
                            <td class="text-success">+{{ deposit.profit }}$</td>
                            {% else %}
                            <td class="text-danger">-{{ deposit.profit }}$</td>
                            {% endif %}
                            <td><a href="{% url 'transactions:edit_deposit' deposit.id %}" type="submit" class="btn ">
                                <img src="{% static 'imgs/Edit.svg' %}" alt="edit">
                            </a></td>
                            <td><a href="{% url 'transactions:delete_deposit' delete_id=deposit.id %}" type="submit" class="btn">
                                <img src="{% static 'imgs/Bin.svg' %}" alt="edit">
                            </a></td>
                        </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>
{% endif %}


<script src="{% static 'navigation.js' %}"></script>
{% endblock %}

essentials/templates/transactions/credit_deposit/edit_credit.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<h1 class="page-name text-center">Edit Credit</h1>
<div class="row">
    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 mx-auto">
      <div class="income-form shadow border-top rounded mb-5">
        <form method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <div class="upperText">
          <label for="inputNumber" class="form-label">Amount</label>
          <input type="number" class="rangeNum" name="credit_amount" id="inputNumber" value="{{ credit.amount }}" min="0" max="100000" oninput="cloneValue(this.value)">
        </div>
        <input type="range" class="range" id="range" min="0" max="100000" step="1" value="{{ credit.amount }}" oninput="getRange(this.value)" />
        <div class="lowerText1">
          <label class="form-label text-center">0</label>
          <label class="form-label text-center">100 000</label>
        </div>
        <div class="lowerText2">
          <label class="form-label text-center">
            Yearly Amount<br>
            <p id="potentialIncome">{{ credit.income }}$</p>
            <input type="hidden" name="credit_income" value="{{ credit.income }}" id="depositIncomeField">
          </label>
          <label class="form-label text-center">
            Loss<br>
            <p id="profitValue">{{ credit.profit }}$</p>
            <input type="hidden" name="credit_loss" value="{{ credit.profit }}" id="depositProfitField">
          </label>
          <label class="form-label text-center">
            Annual percentage<br>
            13.9%
          </label>
        </div>
      </div>

      <div class="d-flex justify-content-center gap-3">
        <button type="submit" class="btn home-button" style="width: 100%;">Update</button>
        <a href="{% url 'transactions:credit' %}" type='button' class="btn btn-cancel" style="width: 100%;">Cancel</a>
      </div>
    </form>
      </div>
    </div>
</div>


    <script>
function percentage(percent, total) {
  return ((parseFloat(total) / 100) * percent).toFixed(2);
}

function getRange(val) {
  const result = parseFloat(val) + parseFloat(percentage(13.9, val));
  document.getElementById("potentialIncome").innerHTML = result;
  document.getElementById("inputNumber").value = val;
  document.getElementById("profitValue").innerText = parseFloat(percentage(13.9, val));

  // Update hidden input field values
  document.getElementById("depositIncomeField").value = result;
  document.getElementById("depositProfitField").value = parseFloat(percentage(13.9, val));
}

function cloneValue(val) {
  if (val > 100000) {
    val = 100000;
    inputNumber.value = val;
  } else if (val <= 0) {
    val = 0;
    inputNumber.value = val;
  }
  document.getElementById("range").value = val;
  const result = parseFloat(val) + parseFloat(percentage(13.9, val));
  document.getElementById("potentialIncome").innerHTML = result.toFixed(2);
  document.getElementById("profitValue").innerText = parseFloat(percentage(13.9, val));

  // Update hidden input field values
  document.getElementById("depositIncomeField").value = result.toFixed(2);
  document.getElementById("depositProfitField").value = parseFloat(percentage(13.9, val));
}

</script>
{% endblock %}

essentials/templates/transactions/credit_deposit/edit_deposit.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<h1 class="page-name text-center">Edit Deposit</h1>
  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 mx-auto">
      <div class="income-form shadow border-top rounded mb-5">
     <form method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <div class="upperText">
          <label for="inputNumber" class="form-label">Amount</label>
          <input type="number" class="rangeNum" name="deposit_amount" id="inputNumber" value="{{ deposit.amount }}" min="0" max="100000" oninput="cloneValue(this.value)">
        </div>
        <input type="range" class="range" id="range" min="0" max="100000" step="1" value="{{ deposit.amount }}" oninput="getRange(this.value)" />
        <div class="lowerText1">
          <label class="form-label text-center">0</label>
          <label class="form-label text-center">100 000</label>
        </div>
        <div class="lowerText2">
          <label class="form-label text-center">
            Yearly Income<br>
            <p id="potentialIncome">{{ deposit.income }}$</p>
            <input type="hidden" name="deposit_income" value="{{ deposit.income }}" id="depositIncomeField">
          </label>
          <label class="form-label text-center">
            Profit<br>
            <p id="profitValue">{{ deposit.profit }}$</p>
            <input type="hidden" name="deposit_profit" value="{{ deposit.profit }}" id="depositProfitField">
          </label>
          <label class="form-label text-center">
            Annual percentage<br>
            11.5%
          </label>
        </div>
      </div>

      <div class="d-flex justify-content-center gap-3">
        <button type="submit" class="btn home-button" style="width: 100%;">Update</button>
        <a href="{% url 'transactions:deposit' %}" type='button' class="btn btn-cancel" style="width: 100%;">Cancel</a>
      </div>
    </form>
      </div>
    </div>
  </div>

<script src="{% static 'navigation.js' %}"></script>
{% endblock %}