Spendy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('transactions/', include('transactions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("login/", views.sing_in, name="login"),
    path("register/", views.sing_up, name="register"),
    path("logout/", views.sign_out, name="logout"),
]

essentials/templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block body %}
    <div class="row">
        <div class="mx-auto col-lg-6 col-md-10">
            <h1 class="mb-4 accent-style text-center">Login Page</h1>
            <form class="login-form" method="POST">

                {% csrf_token %}
                <div class="mb-3">
                    <label for="InputEmail" class="form-label">Email</label>
                    <input type="email" name="email" class="form-control" id="InputEmail" aria-describedby="emailHelp">
                    <div id="emailHelp" class="form-text">We won't share your email with anyone</div>
                </div>
                <div class="mb-3">
                    <label for="InputPassword" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="InputPassword">
                </div>
                <button type="submit" class="btn account-button mt-2">
                    Login
                </button>
            </form>
            <div class="mt-3 account-link">
                Not a member? <a
                    href="{% url "users:register" %}">Register here</a>
            </div>
        </div>
    </div>


{% endblock %}

essentials/templates/accounts/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-6 col-md-10 mx-auto">
        <h1 class="mb-4 accent-style text-center">Sing Up Page</h1>
            <form class="signup-form" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="InputEmail" class="form-label">Email</label>
                    <input type="email" name="email" class="form-control" id="InputEmail" aria-describedby="emailHelp">
                    <div id="emailHelp" class="form-text">We won't share your email with anyone</div>
                </div>
                <div class="mb-3">
                    <label for="InputPassword" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="InputPassword">
                </div>
                <button type="submit" class="btn account-button mt-2">
                    Sign Up
                </button>
            </form>
            <div class="mt-3 account-link">
                Already a member? <a
                    href="{% url "users:login" %}">Login here</a>
            </div>
        </div>
    </div>
{% endblock %}